---
dist: xenial
git:
  depth: 100
language: python
python:
  - "3.6"
  # - "3.7"
services:
  - docker
env:
  global:
    - INSPEC_SHASUM = "1c9ccb80ba39484115d4c1d7e2b1258615e9c56079f86963dee9fb2120b94dc3"
    - INSPEC_VERSION=3.7.1
    - INSPEC_PKG=inspec_${INSPEC_VERSION}-1_amd64.deb
install:
  - pip install tox-travis codecov
  - curl -L https://packages.chef.io/files/stable/inspec/${INSPEC_VERSION}/ubuntu/16.04/${INSPEC_PKG} -o ${INSPEC_PKG}
  - [[ $(sha256sum ${INSPEC_PKG}) = ${INSPEC_SHASUM} ]] && dpkg -i ${INSPEC_PKG}
script:
  - tox
after_success:
  - (cd .tox/ && codecov -v -X gcov --required)
